name: CI
'on':
  push:
    branches:
      - feature/**
      - fix/**
      - docs/**
  pull_request:
    branches:
      - master
      - dev
jobs:
  linting:
    strategy:
      matrix:
        node:
          - 12
          - latest
      fail-fast: true
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '${{ matrix.node }}'
      - name: Install dependencies
        run: npm install
      - name: lint and format
        run: npm run fmt
  tests:
    strategy:
      matrix:
        node:
          - 12
          - latest
      fail-fast: true
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '${{ matrix.node }}'
      - name: Install dependencies
        run: npm ci
      - name: Unittests
        run: npm run test
  build:
    strategy:
      matrix:
        node:
          - 12
          - latest
      fail-fast: true
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '${{ matrix.node }}'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
