name: CI
'on':
  push:
    branches:
      - feature/**
      - fix/**
      - docs/**
      - refactor/**
      - master
      - dev
jobs:
  linting:
    strategy:
      matrix:
        node:
          - 12
          - 14
      fail-fast: true
    runs-on: ubuntu-latest
    name: Lint (node_${{ matrix.node }})
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '${{ matrix.node }}'
      - name: Install dependencies
        run: npm install
      - name: lint and format
        run: npm run fmt
  tests:
    strategy:
      matrix:
        node:
          - 12
          - 14
      fail-fast: true
    runs-on: ubuntu-latest
    name: Test (node_${{ matrix.node }})
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '${{ matrix.node }}'
      - name: Install dependencies
        run: |
          npm ci
      - name: Unittests
        run: npm test
  build:
    strategy:
      matrix:
        node:
          - 12
          - 14
      fail-fast: true
    runs-on: ubuntu-latest
    name: Build (node_${{ matrix.node }})
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '${{ matrix.node }}'
      - name: Install dependencies
        run: |
          npm ci
      - name: Build web
        run: npm run build:web
 
      - name: Build cli
        run: npm run build:cli
 